// File generated by FlutterFire CLI — do not modify by hand.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web not configured. Use flutterfire configure for Web.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Unsupported platform: $defaultTargetPlatform');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx9W5hBV9f4DZV-Nd-eZR7r6hOPlmw5zo',
    appId: '1:194668633640:android:2edff79c0cde72045d1f1d',
    messagingSenderId: '194668633640',
    projectId: 'sample-social-dfdb2',
    databaseURL: 'https://sample-social-dfdb2-default-rtdb.firebaseio.com',
    storageBucket: 'sample-social-dfdb2.appspot.com',
  );

  // Add iOS config here if you register the app on Firebase console for iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '194668633640',
    projectId: 'sample-social-dfdb2',
    databaseURL: 'https://sample-social-dfdb2-default-rtdb.firebaseio.com',
    storageBucket: 'sample-social-dfdb2.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.neatroots.sampleSocial',
  );
}
